---
# This workflow allows for manual updating of
# armory docker images from github actions.

name: armory-image-update

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Specify Arguments"
jobs:
  update-image:
    name: Update Image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.branch }}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Build image
        run: |
          echo "Running python build.py ${{github.event.inputs.tags}}"
          python build.py ${{github.event.inputs.tags}}
      - name: Test Image
        run: |
          echo "Testing Image"
          echo "**not done yet**"
      - name: Push Image
        run: |
          echo "Pushing Image"
